[package]
name = "cify"
description = "A deserializer for the Common Interface File used for exchanging train schedule information in the UK"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "2.0.12"
